Ajouts ms.
Autograph
Autograph manuscript
Copie du Bureau de la copie de l'Opéra
Libretto, handwritten
Libretto, printed
Manuscript copy
Manuscript copy with autograph annotations
Ms
Ms autogr.
Ms. 
Ms. (autogr. ?)
Ms. (non autogr.)
Ms. autogr
Ms. autogr. 
Ms. autogr. (en partie ?)
Ms. autogr. ?
Ms. autogr. de Berton
Ms. autogr. de Francoeur
Ms. autogr. de L.-J. Francoeur
Ms. autogr. de Trial
Ms. autogr. et ms.
Ms. autogr.?
Ms. avec insertions imprimées
Ms. en partie autogr.
Ms. en partie autogr. de Jean-Baptiste Lully
Ms. et éd.
Ms. et ms. autogr.
Ms. frç.
Ms. non autogr.
Ms., avec p. de t. imprimée
Mus.
Musique imprimée et ms. autogr.
Nouvelle et dernière Edition, contenant les corrections Jugées // convenables et nècessaires par les auteurs, dont l'intention est, qu'il ne soit // fait dans quelque partie que ce puisse être, aucune espece de changement // à cet ouvrage s'il arrive qu'on le mette de nouveau sous les yeux du // public
Other
Partial autograph
Possible autograph manuscript
Print
Print with autograph annotations
Print with non-autograph annotations
Probably autograph
Treatise, handwritten
Treatise, printed
[Ajouts ms. en partie autogr.]
[Ajouts ms. partiellement autogr.]
[Ajouts ms.]
[Edition avec ajouts ms.]
[Exemplaire avec corrections autographes]
[Épreuves corrigées autographes]
[Partie]
copie de l'atelier Lanciani
copie de l'atelier Philidor
ms
ms.
ms. et impr.
