DELIMITER $$
DROP FUNCTION IF EXISTS SUBSTR_DELIM $$
DROP FUNCTION IF EXISTS STR_COUNT$$

CREATE FUNCTION STR_COUNT(txt TEXT, c VARCHAR(10)) RETURNS INTEGER
BEGIN
  DECLARE FOUND INTEGER;
  SELECT 
  ROUND ( ( LENGTH(txt) - LENGTH( REPLACE ( txt, c, "" )  )  ) / LENGTH(c) )    
  INTO FOUND;
  RETURN FOUND;
END $$

CREATE FUNCTION SUBSTR_DELIM(txt TEXT, delim1 VARCHAR(10), delim2 VARCHAR(10), pos INTEGER) RETURNS TEXT
BEGIN
  DECLARE STR_FOUND TEXT;
  DECLARE RESULT TEXT;
  DECLARE ROWS_FOUND INT;
  IF (STR_COUNT(txt, delim1) >= STR_COUNT(txt, delim2)) THEN SELECT STR_COUNT(txt,delim2) INTO ROWS_FOUND;
  ELSE SELECT STR_COUNT(txt, delim1) INTO ROWS_FOUND;
  END IF;
  IF (pos <= ROWS_FOUND) THEN 
  SELECT substring_index( substring_index(txt, delim2, pos), delim1, -1) 
  INTO STR_FOUND;
  END IF;
  IF (INSTR(STR_FOUND, '=') = 0) THEN SELECT STR_FOUND INTO RESULT;
  END IF;
  RETURN RESULT;
END $$

DELIMITER ;
